{
    'name': " Support Tickets Bytacora",
    'version': "1.1.0",
    'author': "Nahuel Costa",
    'category': "Tools",
    'summary': "Support ticket system",
    'description': "Support ticket system",
    'data': [
	 'security/helpdesk_bytacora_security.xml',
	 'views/support_ticket_view.xml',
	 'views/support_ticket_menu.xml',
	 'views/support_ticket_others.xml',
	 'views/support_ticket_solution.xml',
     'views/support_ticket_reassignation.xml',
     'data/helpdesk.bytacora.ticket.categories.xml',
     'data/helpdesk.bytacora.ticket.priorities.xml',
	 'data/helpdesk.bytacora.ticket.users.xml',
	 'data/ir_sequence_data.xml',
	 'security/ir.model.access.csv',
     'security/helpdesk_bytacora_rules.xml',
    ],
    'demo': [],
    'depends': ['mail','project'],
    'images':[
        'static/description/logo.png',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}